### PR TITLE
removed CHAIN_ID constant

### PR DESCRIPTION
**Pull request by tritone11**
With a CHAIN_ID constant in a private module it is impossible to sign transactions for a private network with a CHAIN_ID different than 1. Adding the parameter in the sign function and removing the constant solves the problem

### CODE REVIEW

**Comment by synlestidae** [comment]
Sorry I didn't see this until now. I agree this crate should allow the user to choose the chain ID. If you can make the following two changes I can merge this. 

* For style requirements, can you please change instances of `CHAIN_ID` to `chainId`? 
* Unit tests demonstrating signing of transactions for ETH and ETC (i.e. cases for chainId=1 and chainId=61
* Bump the crate version to 1.0.0 since it is a breaking change for dependent crates.

**Comment by synlestidae** [comment]
Yes whoops should have specified `chain_id`. Good find with the leading zeros! I'll handle that one and make sure it conforms to the Eth spec. I may add more tests.

**Comment by tritone11** [comment]
About the leading zeros, my last change on the master of my fork is
<pre>
        let mut R = sig.r;		
	let mut S = sig.s;		
	while R[0] == 0 {		
	    R.remove(0);		
	}		
	while S[0] == 0 {		
	    S.remove(0);		
	}
        let mut tx = RlpStream::new(); 
        tx.begin_unbounded_list();
        self.encode(&mut tx);
        tx.append(&sig.v); 
        tx.append(&R); 
        tx.append(&S); 
</pre>
Although I don't like whiles, they sholdn't be resource consuming as they run mostly only for zero or one loop and it totally fixed the problem for me.  
If you are fine with it I will put it also in this pull request!

**Comment by synlestidae** [comment]
That's perfectly fine. I was working on the zeros issue myself. I want to put some tests in, with signed transactions generated by another Eth library (it's in the `pr-3` branch).

Been delayed because I want to test this thoroughly before release. Feel free to look at the `pr-3` branch. So far one test fails and I am working out if it was a problem with the test data and/or implementation

**Pull request merged**
